### PR TITLE
Add authentication file support

### PR DESCRIPTION
**Pull request by lgirault**
This is useful to access private repositories. 
Also support a `$env_var` format for better flexibility

### CODE REVIEW

**Comment by ianoc** [comment]
@lgirault this looks good to me, but could you add a test? it doesn't seem that the new parsing code is covered in a test now I believe. 

Something in https://github.com/johnynek/bazel-deps/blob/120e27a76a8bfa367ce4f1b6860a9530b84731bc/test/scala/com/github/johnynek/bazel_deps/ParseTest.scala

**Comment by lgirault** [comment]
Sure ! Is that enough ?

**Comment by lgirault** [comment]
I'm not sure what to do. I think the broken test is not linked to my PR. 
Furthermore, locally I ran it twice: it failed once and passed once.
I'll try to investigate it as soon as I have some free time

**Comment by ianoc** [comment]
Does seem unrelated to your change, i restarted the build and its passed now. So i'm going to merge this.

Thanks for the contribution! Sorry again for the slow replies

**Pull request merged**
