### PR TITLE
Get rules_scala updated / back on master

### PR DESCRIPTION
**Pull request by travisbrown-stripe**
The rules_scala version is currently pointing at a commit that's not on master, which results in errors like this:

```
bazel-deps git:(master) bazel build //...
ERROR: error loading package '': Encountered error while reading extension file 'scala/scala.bzl': no such package '@io_bazel_rules_scala//scala': Missing unknown c5f7fae8d7540148b78a8d1cecef459397dbb62b
ERROR: error loading package '': Encountered error while reading extension file 'scala/scala.bzl': no such package '@io_bazel_rules_scala//scala': Missing unknown c5f7fae8d7540148b78a8d1cecef459397dbb62b
INFO: Elapsed time: 10.066s
FAILED: Build did NOT complete successfully (0 packages loaded)
```
I just updated to latest master, which also requires registering the toolchains.

r? @gkk-stripe

### CODE REVIEW

**Comment by gkk-stripe** [comment]
to make ci pass, you need to bump the bazel version used in ci, it's pinned at 0.7: https://github.com/johnynek/bazel-deps/blob/master/.bazel-installer-linux-x86_64.sh.sha256
i'd vote for something more recent, like 0.10 or 0.11

**Comment by johnynek** [comment]
happy to merge when we get CI green.

**Comment by travisbrown** [comment]
I bumped it to 0.11.1 but happy to change to another version.

**Comment by johnynek** [comment]
seems fine, but looks like it is fetching the 0.7 version still in the .travis.yaml file:

https://github.com/johnynek/bazel-deps/blob/master/.travis.yml#L19

**Pull request merged**
