### PR TITLE
Add mkdir to update_dependencies.sh

### PR DESCRIPTION
**Pull request by snoble**
I haven't actually seen this build or run yet

### CODE REVIEW

**Comment by snoble** [comment]
While we're here, do you really want `--disable-3rdparty-in-repo` in this script?

**Comment by ianoc** [comment]
Yep! its generally better not to have the 3rdparty in the repo.

Users can edit it out if they wish. but if you have any of these repos depend on one another the external repo ensures they talk about the same one. If its inside the repo you can have different class paths for the one target happening.

**Comment by snoble** [comment]
Gotcha! I asked because it ended up confusing me. I didn't get to the point in the docs where it described how to use `Alternate outputs, external repo` and just saw that I wasn't getting the files I expected from `Usage`.

**Comment by ianoc** [comment]
Not to abuse your PR skills, but if you have the time, any updated wording that would have helped you here would be great.

**Pull request merged**
