### PR TITLE
Restrict the visibility of transitive depdendencies.

### LINKED ISSUE #99: Make indirect dependencies have restricted visibility
Right now, all the generated targets have `visibility = ["//visibility:public"]`. This allows a kind of strict dependency violation where a build target could depend on a maven artifact not mentioned in the yaml file.

The targets for the indrect dependencies should have `visibility = ["//${thirdPartyDirectory}:__subpackages__"]` so that they can only be referenced by targets under the third party directory.

Originally https://github.com/johnynek/bazel-deps/issues/98#issuecomment-349928980

### PR DESCRIPTION
**Pull request by arjantop**
WIP.

Fixes #99

### CODE REVIEW

**Comment by johnynek** [comment]
Seems like a good change, but I only took a pretty quick look. What do you have in mind before removing the WIP?

Thanks for the PR!

**Comment by arjantop** [comment]
@johnynek I wrote about the missing features in #99

**Comment by johnynek** [comment]
closed in favor of #165 (mostly because like a fool, I forgot about this PR).

**Comment by arjantop** [comment]
@johnynek no worries, I was totally preoccupied and this slipped my mind

Great that this is finally implemented and merged 👍

**Pull request closed without merging**
