### PR TITLE
Bump rules_scala

### LINKED ISSUE #241: Bazel 0.23.0 compatibility
As of today Bazel `0.23.0` has been released -> https://github.com/bazelbuild/bazel/issues/6495. Throwing up this issue to track `0.23.0` compatibility. 

The error appears pretty simple to (short-term) fix: 

```
ERROR: /private/var/tmp/_bazel_jbelotti/a8760d5b2ababb5105592d0d98b41ced/external/io_bazel_rules_scala/scala/scala.bzl:111:13:
Using cfg = "data" on an attribute is a noop and no longer supported. 
Please remove it. You can use --incompatible_disallow_data_transition=false to temporarily disable this check.
```

### PR DESCRIPTION
**Pull request by mjduijn**
Now builds without warnings in Bazel 0.23.0 

Resolves #241

### CODE REVIEW

**Comment by johnynek** [comment]
Thank you so much!

I think we will need to bump the travis CI version of bazel used:
https://github.com/johnynek/bazel-deps/blob/master/.travis.yml

I guess at least 0.22 will be required.

**Comment by Jdban** [comment]
You could do something like [startup-os](https://github.com/google/startup-os)  does where the bazel version is specified in a `.bazelversion` file and automatically downloaded and used via the `tools/bazel` script. 

That way, CI and all local builds use the same version bazel and it can be changed easily across branches. You might want to remove the `rm` line though b/c it's annoying locally if the version gets deleted and redownloaded when switching branches.

https://github.com/google/startup-os/blob/ceac236a2d6d3f1b95d8da9d1f044f30d9a4680c/tools/bazel

**Comment by mjduijn** [comment]
I could also include a Bazel version check from [bazel-skylib](https://github.com/bazelbuild/bazel-skylib/blob/1b28145983091cbe8639d2816fb03ccb3950bbc9/lib/versions.bzl#L82).

    load("@bazel_skylib//lib:versions.bzl", "versions")
    
    versions.check(minimum_bazel_version = "0.22.0")

@johnynek your call

**Comment by johnynek** [comment]
Happy to take the version check in a follow up if you like.

Thank you!

**Comment by thundergolfer** [comment]
@mjduijn cheers!

**Pull request merged**
