### PR TITLE
Update rules_scala to pull in https for central.maven.org

### PR DESCRIPTION
**Pull request by yonajune**
Trying to pull in https://github.com/bazelbuild/rules_scala/pull/920

Changes since the last update:
https://github.com/bazelbuild/rules_scala/compare/0f89c21...a676633

### CODE REVIEW

**Comment by abhandaru** [comment]
Nice. Did they publish it?

**Comment by yonajune** [comment]
> Nice. Did they publish it?

(Assuming you mean `rules_scala`)

Very little context, so happy to be corrected. I think `git_repository` function used here based on the [Bazel docs](https://docs.bazel.build/versions/master/repo/git.html) just needs the commit SHA to be updated, which I provided.

**Comment by radix-aw** [comment]
@yonajune Thank you for this. Looking forward to it being merged ASAP.

**Comment by johnynek** [comment]
thanks for the PR!

**Pull request merged**
