### PR TITLE
add a test to fix some excludes on Coursier

### LINKED ISSUE #149: Stack trace using coursier resolverType w/ excludes
While attempting to support classifiers for the coursier resolverType in #134, I ran into an issue, and narrowed it down to the following set of dependencies, and I can reproduce it on master without my changes:

```
dependencies:
  com.lowagie:
    itext:
      lang: java
      version: "2.1.7"
      exclude:
        - "bouncycastle:bcprov-jdk14"
        - "bouncycastle:bcmail-jdk14"
        - "bouncycastle:bctsp-jdk14"
  org.xhtmlrenderer:
    flying-saucer-pdf:
      lang: java
      version: "9.0.3"
```

`flying-saucer-pdf` depends on `com.lowagie:itext`. The aether resolver (correctly, IMO), completely excludes the `bouncycastle` deps from this graph. Based on logging I added around line 170 in CoursierResolver.scala, it looks like `res.finalDependenciesCache` includes _two_ entries for `com.lowagie:itext` for this graph, one which correctly excludes the `bouncycastle` deps, and one which doesn't exclude them (presumably this is the indirect reference from flying-saucer-pdf). 

The stack trace I get is:

```
[main] ERROR MakeDeps - resolution and sha collection failed
java.lang.RuntimeException: no artifacts for bouncycastle:bctsp-jdk14:138 found
        at com.github.johnynek.bazel_deps.CoursierResolver$$anonfun$com$github$johnynek$bazel_deps$CoursierResolver$$lookup$1$1.apply(CoursierResolver.scala:130)
        at com.github.johnynek.bazel_deps.CoursierResolver$$anonfun$com$github$johnynek$bazel_deps$CoursierResolver$$lookup$1$1.apply(CoursierResolver.scala:116)
        at coursier.util.Task$$anonfun$flatMap$extension$1$$anonfun$apply$1.apply(Task.scala:10)
        at coursier.util.Task$$anonfun$flatMap$extension$1$$anonfun$apply$1.apply(Task.scala:10)
        at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:253)
        at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:36)
        at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

It seems like there shouldn't be any attempt to fetch the `bouncycastle` deps in this instance, since they should be excluded?

### PR DESCRIPTION
**Pull request by johnynek**
fixes #149 

Not sure why this is needed since we are communicating excludes to coursier, but it seems like it wouldn't hurt to make sure we don't put the edges in the final graph.

@roblg please take a look

cc @ianoc-stripe maybe this fixes our issues as well?

### CODE REVIEW

**Comment by ianoc-stripe** [comment]
I'll test this out on a branch i have internally

**Comment by ianoc-stripe** [comment]
Yeah with these changes our excludes work more uniformly. So fixes our problems!

**Comment by roblg** [comment]
Thanks @johnynek. This fixes the issue #149 for me.

**Comment by johnynek** [comment]
@roblg thanks for testing. I’ll try to address any bugs reports you make ASAP especially if you can find small repros

Thanks again!

**Pull request merged**
