### PR TITLE
Fix sha file path bug

### LINKED ISSUE #48: gen_maven_deps.sh no longer working on OSX
I just updated this repo after a few months.  It no longer works as expected on OSX:

It seems to generate a full path from the cwd to the workspace directory now, e.g. `ROOT/Users/seanmcl/foo/...`.  See below.

```

$ cd ~/tmp/foo 
$ git clone https://github.com/johnynek/bazel-deps.git
Cloning into 'bazel-deps'...
...
$ ls
bazel-deps  dependencies.yaml
$ cd bazel-deps
$ git log -1
d886f0566f867329b0f5c559edf41781c67eebca
...
$ bazel build src/scala/com/github/johnynek/bazel_deps:parseproject_deploy.jar
...........
INFO: Found 1 target...
...
$ cd ..
$ ls
bazel-deps  dependencies.yaml
$ ./bazel-deps/gen_maven_deps.sh generate -r `pwd` -s 3rdparty/workspace.bzl -d dependencies.yaml
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
wrote 90 targets in 39 BUILD files
$ ls
3rdparty  Users  bazel-deps  dependencies.yaml  target
$ ls 3rdparty
jvm
$ find Users
Users
Users/seanmcl
Users/seanmcl/tmp
Users/seanmcl/tmp/foo
Users/seanmcl/tmp/foo/3rdparty
Users/seanmcl/tmp/foo/3rdparty/workspace.bzl
```

### PR DESCRIPTION
**Pull request by seanmcl**
Fixes #48

### CODE REVIEW

**Comment by seanmcl** [comment]
I don't understand the Travis failure.  Is it from my change?  Something about scallop.

**Comment by johnynek** [comment]
we have a test that running the code on the repo creates a clean diff, but since the code was broken (for a reason I still don't understand) after I removed scallop, this test is failing.

if you run the tool on the repo, you can fix this issue.

**Comment by seanmcl** [comment]
Done.

**Comment by johnynek** [comment]
Okay, I just accidentally broke this here:

https://github.com/johnynek/bazel-deps/pull/42/files#r125134706

by adding the root path when in fact it is done in the `IO` interpreter. Thanks for fixing this.

**Pull request merged**
